# Generated by Django 4.2.16 on 2024-11-19 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.TextField(blank=True, null=True)),
                ('card_link', models.URLField(blank=True, null=True)),
                ('card_apply_link', models.URLField(blank=True, null=True)),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='card_images/')),
                ('notification', models.TextField(blank=True, null=True)),
                ('annual_fee', models.TextField(blank=True, null=True)),
                ('base_performance', models.TextField(blank=True, null=True)),
                ('base_performance_last_month', models.TextField(blank=True, null=True)),
                ('merit_summary', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Decile_consume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_range', models.TextField()),
                ('worker', models.FloatField()),
                ('not_worker', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Decile_income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_range', models.TextField()),
                ('worker', models.FloatField()),
                ('not_worker', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DepositProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(unique=True)),
                ('kor_co_nm', models.TextField()),
                ('fin_prdt_nm', models.TextField()),
                ('etc_note', models.TextField()),
                ('join_deny', models.IntegerField()),
                ('join_member', models.TextField()),
                ('join_way', models.TextField()),
                ('spcl_cnd', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Incomepergenderage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.TextField()),
                ('agerange', models.TextField()),
                ('avgallincome', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Incomepergrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.TextField()),
                ('avgincome', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Incomeperjob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.TextField()),
                ('avgincome', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='IncomeSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_range', models.TextField()),
                ('worker', models.FloatField()),
                ('not_worker', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SavingProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.IntegerField(blank=True, default=1, null=True)),
                ('fin_co_no', models.TextField(blank=True, default=1, null=True)),
                ('fin_prdt_cd', models.TextField(default=1, unique=True)),
                ('kor_co_nm', models.TextField(blank=True, default=1, null=True)),
                ('fin_prdt_nm', models.TextField(blank=True, default=1, null=True)),
                ('join_way', models.TextField(blank=True, default=1, null=True)),
                ('mtrt_int', models.TextField(blank=True, default=1, null=True)),
                ('spcl_cnd', models.TextField(blank=True, default=1, null=True)),
                ('join_deny', models.IntegerField(blank=True, default=1, null=True)),
                ('join_member', models.TextField(blank=True, default=1, null=True)),
                ('etc_note', models.TextField(blank=True, default=1, null=True)),
                ('max_limit', models.TextField(blank=True, default=1, null=True)),
                ('dcls_strt_day', models.IntegerField(blank=True, default=1, null=True)),
                ('dcls_end_day', models.IntegerField(blank=True, default=1, null=True)),
                ('fin_co_subm_day', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(blank=True, default=1, null=True)),
                ('intr_rate_type_nm', models.CharField(max_length=100)),
                ('rsrv_type', models.TextField(blank=True, default=1, null=True)),
                ('intr_rate', models.FloatField(blank=True, default=1, null=True)),
                ('intr_rate2', models.FloatField(default=-1)),
                ('save_trm', models.IntegerField(blank=True, default=1, null=True)),
                ('product2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.savingproducts')),
            ],
        ),
        migrations.CreateModel(
            name='DepositOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField()),
                ('intr_rate_type_nm', models.CharField(max_length=100)),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField(default=-1)),
                ('save_trm', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.depositproducts')),
            ],
        ),
    ]
