# Generated by Django 4.2.16 on 2024-11-21 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0003_community_decile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='community_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
