# Generated by Django 4.2.16 on 2024-11-21 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_alter_community_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='user',
        ),
    ]
