# Generated by Django 4.2.16 on 2024-11-21 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0007_remove_community_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='joined_communities', to=settings.AUTH_USER_MODEL),
        ),
    ]
