# Generated by Django 4.2.16 on 2024-11-21 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0008_community_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
