# Generated by Django 4.2.16 on 2024-11-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='consume',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='desire_period',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='financial_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='income',
            field=models.IntegerField(default=0),
        ),
    ]
