# Generated by Django 4.2.16 on 2024-11-21 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_community_decile'),
        ('accounts', '0003_alter_user_age_alter_user_consume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='communities.community'),
        ),
    ]
