# Generated by Django 4.2.16 on 2024-11-21 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_alter_community_user'),
        ('accounts', '0006_remove_user_community_alter_user_communities'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_foreignkey', to='communities.community'),
        ),
    ]
