# Generated by Django 4.2.16 on 2024-11-21 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_communities_remove_user_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='communities',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
