# Generated by Django 4.2.16 on 2024-11-21 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_communities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='communities',
        ),
    ]
