# Generated by Django 4.2.16 on 2024-11-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_alter_community_user'),
        ('accounts', '0011_remove_user_communities'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='communities',
            field=models.ManyToManyField(blank=True, related_name='members', to='communities.community'),
        ),
    ]
