# Generated by Django 4.2.16 on 2024-11-22 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email'),
        ('accounts', '0014_user_community_alter_user_communities'),
    ]

    operations = [
    ]
