# Generated by Django 4.2.16 on 2024-11-22 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_merge_20241122_0939'),
        ('accounts', '0015_merge_20241122_0945'),
    ]

    operations = [
    ]
