# Generated by Django 4.2.16 on 2024-11-22 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_merge_20241122_1411'),
        ('accounts', '0016_merge_20241122_1423'),
    ]

    operations = [
    ]
