# Generated by Django 4.2.16 on 2024-11-24 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_merge_20241123_1244'),
        ('accounts', '0018_merge_20241123_1707'),
    ]

    operations = [
    ]
