# Generated by Django 4.2.16 on 2024-11-24 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_merge_20241123_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_analysis', models.TextField()),
                ('income_decile', models.CharField(max_length=50)),
                ('spending_analysis', models.TextField()),
                ('job_analysis', models.TextField()),
                ('grade_analysis', models.TextField()),
                ('card_recommendations', models.JSONField(blank=True, default=list, null=True)),
                ('deposit_recommendations', models.JSONField(blank=True, default=list, null=True)),
                ('saving_recommendations', models.JSONField(blank=True, default=list, null=True)),
                ('tax_refund_estimation', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
