# Generated by Django 4.2.16 on 2024-11-24 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_merge_20241124_1127'),
        ('accounts', '0020_report'),
    ]

    operations = [
    ]
