# Generated by Django 4.2.16 on 2024-11-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_report_saving_recommendations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='saving_recommendations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='tax_refund_estimation',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
