# Generated by Django 4.2.16 on 2024-11-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_report_saving_recommendations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_decile',
            field=models.IntegerField(default=0),
        ),
    ]
