# Generated by Django 4.2.6 on 2024-11-20 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=255)),
                ('card_image', models.CharField(max_length=255)),
                ('notification', models.TextField()),
                ('annual_fee', models.CharField(max_length=255)),
                ('base_performance', models.TextField()),
                ('base_performance_last', models.TextField(blank=True, null=True)),
                ('merit_summary', models.TextField()),
                ('card_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.carddesign')),
            ],
        ),
    ]
